repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--django]
      - id: pretty-format-json
        args: [--autofix]

  - repo: https://gitlab.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v0.931'
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         # - strawberry-graphql
  #         - django-stubs
  #         - django-stubs-ext
  #         - django-environ
  #       exclude: "^.*/migrations/|^.*/settings.py"  # file名を渡しているので、pyproject.tomlの設定が効かない！

  - repo: local  # 人の環境によって動作が異なる可能性があるので好ましくない？
    hooks:
      - id: mypy
        language: system
        name: check py typing
        entry: mypy .
        pass_filenames: false
        always_run: true
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: '21.12b0'
    hooks:
    - id: black
      args:
        - --check
      language_version: python3
      exclude: ^.*/migrations/  # file名を渡しているので、pyproject.tomlの設定が効かない！

  - repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        args:
          - --check-only
        exclude: "^.*/migrations/|account|store"  # file名を渡しているので、pyproject.tomlの設定が効かない！
        additional_dependencies:
          - toml

  - repo: local
    hooks:
      - id: migrations-check
        language: system
        name: Check for uncreated migrations.
        entry: sh -c "./manage.py makemigrations --check --dry-run"
        files: "models\\.py$"
        stages: [commit]
